### PR TITLE
Add reset_dagruns to backfill

### PR DESCRIPTION
**Pull request by nicklyz**

### CODE REVIEW

**Comment by sudhakar-nallam** [comment]
@nicklyz Are you able to get this reset_dagruns option working? When I run the same command through airflow command line it is asking for confirmation.

**Comment by nicklyz** [comment]
yea I got this to working. What version of airflow are you on? Mine is 1.10.2

**Comment by sudhakar-nallam** [comment]
@nicklyz I can't get this working. What I mean is that it is asking for Delete confirmation if there are any failed/scheduled/other statuses for Task Instances. Do you know how to bypass this confirmation? 

> You are about to delete these 4 tasks:
 <TaskInstance: make_coffee.make_coffee 2019-09-13 00:00:00+00:00 [scheduled]>
 <TaskInstance: make_coffee.make_coffee 2019-09-13 13:44:59.851967+00:00 [None]>
 <TaskInstance: make_coffee.time_for_coffee 2019-09-13 00:00:00+00:00 [up_for_reschedule]>
 <TaskInstance: make_coffee.time_for_coffee 2019-09-13 13:44:59.851967+00:00 [None]>
Are you sure? (yes/no):

**Review by rssanders3 — CHANGES_REQUESTED** [review]
As per the conversation, can we bypass the Delete Confirmation for reset_dagruns option?

**Comment by michalsosn** [comment]
Since 1.10.6 (the latest version) backfill has a --yes flag that skips the confirmation.
https://airflow.apache.org/docs/stable/cli.html#backfill
So this PR is hopefully unblocked.

**Pull request closed without merging**
