### PR TITLE
Update to support airflow v1.10 with rbac

### LINKED ISSUE #22: Compatibility with RBAC
Hi,

when i star using the RBAC functionality with v2.0, the admin link doesn't exist anymore, is there a way i can still use the plugin with the new links starting with /home ?

### PR DESCRIPTION
**Pull request by atiftw**
This resolves #22 #35 #41

### CODE REVIEW

**Comment by Hasan-J** [comment]
Hello, I'm in need of a friendly advice. I'm using the puckel image (latest airflow 1.10) and I've added this plugin as a volume with docker-compose as explained on the main puckel repo. But here is the problem that I'm facing:
image

I used your PR too, didn't work. Have you faced anything like that or do you know what's wrong ?

Thanks in advance XD

**Comment by atiftw** [comment]
Hi,

You're getting the above error because you have not defined the rest_api_plugin configuration in your airflow.cfg.Attaching my test config here for your reference

```
[rest_api_plugin]
log_loading=True
filter_loading_messages_in_cli_response=False
rest_api_plugin_http_token_header_name=rest_api_plugin_http_token
rest_api_plugin_expected_http_token=None 
```
Additionally there is a bug in some versions of puckel airflow that do not set Airflow home correctly, if that is the case you will also need to set $AIRFLOW_HOME in case this still doesn't work for you.

PS-:I think this may not be the best place to chat so if you have any further issues please message me separately.

Cheers

**Comment by Knowa42** [comment]
Atiftw,
   This looks awesome, exactly what I've been needing. I installed your changes into the plugin in my local deployment, but the endpoints are giving me 404 status when I try to hit them. My assumption was that your changes  would move the version endpoint from
```
/admin/rest_api/api?api=version
```

to

```
/rest_plugin_api/api?api=version
```

Is that correct?

**Comment by atiftw** [comment]
Yes,

Steps to get it to work

1.Set Airflow home 
2.Place plugins under Airflow home directory inside a folder called plugins

Should look like
```
$AIRFLOW_HOME/plugins
...rest_api_plugin.py
...templates/
```

3.In airflow.cfg add the rest plugin properties (From above)
4.Boot airflow 

You should see ```Initializing Airflow REST API Plugin with configs:```

Admin page can be found at ```http://localhost:8080/rest_plugin_api/``` and should also be available in the dropdown

And the api can be invoked 
http://localhost:8080/rest_plugin_api/api?api=rest_api_plugin_version

Tested using the latest airflow master

**Comment by sudhakar-nallam** [comment]
Added support for RBAC in the release https://github.com/teamclairvoyant/airflow-rest-api-plugin/releases/tag/v1.0.8

**Pull request closed without merging**
